#!/usr/bin/env python3
"""Embeds a program (an ELF) into a C source file as a byte array.

Usage: gen_blob.py <output.c> <elf-file> <symbol> [token-mark]

Writes `const unsigned char <symbol>[]` and `const unsigned long <symbol>_len`. It is what puts the install helper
(src/helper/pkginst_helper.c) into the app: the app hands the bytes to the payload loader, one helper for one
installation.

With a token mark named, the build stops unless that mark stands in the file exactly once and is followed by the
placeholder the app writes its token over (src/pkginst_ipc.h: the mark and 16 dots). The app looks for the same place
at run time and refuses an image that has none or two; a build that got there would have shipped an installer that
cannot start anything.
"""
import os
import sys

ELF_MAGIC = b"\x7fELF"
MIN_BYTES = 1024
PLACEHOLDER = b"." * 16


def main():
    if len(sys.argv) < 4:
        sys.exit("usage: gen_blob.py <output.c> <elf-file> <symbol> [token-mark]")
    out_path, elf_path, symbol = sys.argv[1], sys.argv[2], sys.argv[3]
    mark = sys.argv[4].encode() if len(sys.argv) > 4 else None

    if not os.path.isfile(elf_path):
        sys.exit("gen_blob: %s nicht gefunden" % elf_path)
    with open(elf_path, "rb") as handle:
        blob = handle.read()
    if len(blob) < MIN_BYTES or blob[:4] != ELF_MAGIC:
        sys.exit("gen_blob: %s ist kein ELF (%d Bytes, beginnt mit %s)." % (elf_path, len(blob), blob[:4].hex(" ")))
    if mark:
        count = blob.count(mark + PLACEHOLDER)
        if count != 1 or blob.count(mark) != 1:
            sys.exit("gen_blob: die Kennungsstelle %s steht %d-mal (mit Platzhalter %d-mal) in %s, erwartet ist genau einmal."
                     % (mark.decode(), blob.count(mark), count, elf_path))

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/* Generated by tools/gen_blob.py - do not edit. */\n\n")
        out.write("const unsigned char %s[] = {\n" % symbol)
        for i in range(0, len(blob), 16):
            out.write("  %s,\n" % ", ".join("0x%02x" % b for b in blob[i:i + 16]))
        out.write("};\n")
        out.write("const unsigned long %s_len = %d;\n" % (symbol, len(blob)))
    print("gen_blob: %s eingebettet (%d KiB) -> %s" % (os.path.basename(elf_path), len(blob) // 1024, out_path))


if __name__ == "__main__":
    main()
