#!/usr/bin/env python3
"""Embeds the tile folder (tile/sce_sys/) into a C source file.

Usage: gen_tile_files.py <output.c> <tile-dir> [<tile.c>]

The app writes these files to /user/app/<id>/sce_sys on the console and asks the
system to register them as a home-screen tile (src/tile.c). What is checked here
is what would otherwise only show on the console, as a tile that never appears:

  - param.json is a JSON object with a titleId of four capitals and five
    digits and a deeplinkUri — and, when tile.c is named, the very id that file
    looks for (PS5TM_TITLE_ID): a tile registered under another id would be
    installed and never found again, and the app would install it at every start;
  - icon0.png and the pictures are PNG files;
  - nothing in sce_sys/ is empty, and the folder holds param.json and icon0.png.

Files with identical content are emitted once and listed under both names.
"""
import hashlib
import json
import os
import re
import sys

PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
TITLE_ID = re.compile(r"^[A-Z]{4}[0-9]{5}$")
REQUIRED = ("param.json", "icon0.png")
MAX_TOTAL = 4 * 1024 * 1024   # the ELF carries this in memory; see Makefile


def die(message):
    sys.exit("gen_tile_files: " + message)


def title_id_of(tile_c):
    with open(tile_c, encoding="utf-8") as handle:
        match = re.search(r'#define\s+PS5TM_TITLE_ID\s+"([^"]+)"', handle.read())
    if not match:
        die("PS5TM_TITLE_ID steht nicht in %s." % tile_c)
    return match.group(1)


def read_tile(tile_dir, expected_id):
    sce_sys = os.path.join(tile_dir, "sce_sys")
    if not os.path.isdir(sce_sys):
        die("Ordner fehlt: %s" % sce_sys)

    files = []
    for name in sorted(os.listdir(sce_sys)):
        full = os.path.join(sce_sys, name)
        if not os.path.isfile(full):
            die("%s ist keine Datei — sce_sys enthält keine Unterordner." % full)
        if name.startswith(".") or "/" in name or "\\" in name:
            die("Ungeeigneter Dateiname in sce_sys: %r" % name)
        with open(full, "rb") as handle:
            blob = handle.read()
        if not blob:
            die("%s ist leer." % full)
        files.append((name, blob))

    names = [n for n, _ in files]
    for need in REQUIRED:
        if need not in names:
            die("%s fehlt in %s." % (need, sce_sys))

    for name, blob in files:
        if name.lower().endswith(".png") and not blob.startswith(PNG_MAGIC):
            die("%s ist keine PNG-Datei (die Kennung fehlt)." % name)
        if name == "param.json":
            try:
                doc = json.loads(blob.decode("utf-8"))
            except ValueError as err:
                die("param.json ist kein gültiges JSON: %s" % err)
            if not isinstance(doc, dict):
                die("param.json muss ein JSON-Objekt sein.")
            tid = doc.get("titleId")
            if not isinstance(tid, str) or not TITLE_ID.match(tid):
                die("param.json: titleId fehlt oder ist keine 9-stellige "
                    "Kennung (4 Buchstaben, 5 Ziffern): %r" % (tid,))
            if expected_id and tid != expected_id:
                die("param.json nennt %s, tile.c sucht %s." % (tid, expected_id))
            if not isinstance(doc.get("deeplinkUri"), str):
                die("param.json: deeplinkUri fehlt — die Kachel hätte kein Ziel.")

    # What the ELF carries, counting a shared file once.
    unique = {hashlib.sha256(b).digest(): len(b) for _, b in files}
    total = sum(unique.values())
    if total > MAX_TOTAL:
        die("Die Kachel-Dateien wiegen %d KiB (Grenze %d KiB). Sie liegen als "
            "Ganzes im Arbeitsspeicher des Programms: 10,5 MB Zuwachs ließen "
            "die Konsole keine Anfrage mehr bedienen. Bilder verkleinern."
            % (total // 1024, MAX_TOTAL // 1024))
    return files, total


def main():
    if len(sys.argv) not in (3, 4):
        sys.exit("usage: gen_tile_files.py <output.c> <tile-dir> [<tile.c>]")
    out_path, tile_dir = sys.argv[1], sys.argv[2]
    expected = title_id_of(sys.argv[3]) if len(sys.argv) == 4 else None
    files, total = read_tile(tile_dir, expected)

    blobs = {}          # content hash -> symbol
    order = []
    for name, blob in files:
        digest = hashlib.sha256(blob).digest()
        if digest not in blobs:
            blobs[digest] = "tile_blob_%d" % len(blobs)
            order.append((blobs[digest], blob))

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        out.write("/* Generated by tools/gen_tile_files.py — do not edit. */\n")
        out.write('#include "tile_files.h"\n\n')
        for sym, blob in order:
            out.write("static const unsigned char %s[] = {\n" % sym)
            for i in range(0, len(blob), 16):
                row = ", ".join("0x%02x" % b for b in blob[i:i + 16])
                out.write("  %s,\n" % row)
            out.write("};\n\n")
        out.write("const ps5tm_tile_file_t ps5tm_tile_files[] = {\n")
        for name, blob in files:
            sym = blobs[hashlib.sha256(blob).digest()]
            out.write('  { "%s", %s, %dUL },\n' % (name, sym, len(blob)))
        out.write("};\n\n")
        out.write("const unsigned ps5tm_tile_file_count =\n"
                  "    sizeof(ps5tm_tile_files) / sizeof(ps5tm_tile_files[0]);\n")

    print("gen_tile_files: %d Datei(en), %d KiB eingebettet -> %s"
          % (len(files), total // 1024, out_path))


if __name__ == "__main__":
    main()
