#!/usr/bin/env python3
"""Embeds the web/ directory into a C source file.

Usage: gen_assets.py <output.c> <web-dir>
"""
import os
import sys

CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css":  "text/css; charset=utf-8",
    ".js":   "application/javascript; charset=utf-8",
    ".json": "application/json",
    ".png":  "image/png",
    ".jpg":  "image/jpeg",
    ".jpeg": "image/jpeg",
    ".svg":  "image/svg+xml",
    ".ico":  "image/x-icon",
}


def emit_bytes(out, name, blob):
    out.write("static const unsigned char %s[] = {\n" % name)
    for i in range(0, len(blob), 16):
        row = ", ".join("0x%02x" % b for b in blob[i:i + 16])
        out.write("  %s,\n" % row)
    out.write("};\n\n")


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_assets.py <output.c> <web-dir>")

    out_path, web_dir = sys.argv[1], sys.argv[2]

    files = []
    for root, _, names in os.walk(web_dir):
        for name in sorted(names):
            full = os.path.join(root, name)
            rel = os.path.relpath(full, web_dir).replace(os.sep, "/")
            files.append(("/" + rel, full))
    files.sort()

    if not files:
        sys.exit("gen_assets.py: no files found in %s" % web_dir)

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/* Generated by tools/gen_assets.py — do not edit. */\n")
        out.write('#include "ps5tm.h"\n\n')

        symbols = []
        for index, (url, full) in enumerate(files):
            with open(full, "rb") as handle:
                blob = handle.read()
            sym = "asset_%d" % index
            emit_bytes(out, sym, blob)
            ext = os.path.splitext(full)[1].lower()
            symbols.append((url, CONTENT_TYPES.get(ext, "application/octet-stream"),
                            sym, len(blob)))

        out.write("const ps5tm_asset_t ps5tm_assets[] = {\n")
        for url, ctype, sym, size in symbols:
            out.write('  { "%s", "%s", %s, %d },\n' % (url, ctype, sym, size))
        out.write("};\n\n")
        out.write("const unsigned ps5tm_assets_count =\n"
                  "    sizeof(ps5tm_assets) / sizeof(ps5tm_assets[0]);\n")

    total = sum(size for _, _, _, size in symbols)
    print("gen_assets: %d Datei(en), %d Bytes -> %s"
          % (len(symbols), total, out_path))


if __name__ == "__main__":
    main()
