#!/usr/bin/env python3
"""Embeds the tile PKG into a C source file for the installer payload.

Usage: gen_pkg_blob.py <output.c> [pkg-file]

With no PKG named, it emits an empty blob and the payload looks for a package
on disk at run time instead. Nothing is auto-discovered: an earlier version
searched pkg/out/ on its own, which quietly put 10 MB back into the app after
it had deliberately been left out.
"""
import os
import sys

# A PS5 package starts 7F 'F' 'I' 'H' (a PS4 one 7F 'C' 'N' 'T'). Nothing
# smaller than a page can be one: the header alone is larger.
PKG_MAGIC = b"\x7fFIH"
PKG_MIN_BYTES = 4096


def read_package(pkg_path):
    """The bytes of a package that is named, or a reason to stop the build.

    A package that is named but cannot be used used to end in an installer that
    looked finished: a missing file and an empty one both became an empty blob
    with exit code 0, and a half-written one (an interrupted packaging run) was
    embedded as it was. The failure then showed up on the console, as an
    installer that found nothing to install or handed the system a file it
    could not read. Only "no package named at all" is the deliberate case.
    """
    if not os.path.isfile(pkg_path):
        sys.exit("gen_pkg_blob: Paket nicht gefunden: %s" % pkg_path)

    with open(pkg_path, "rb") as handle:
        blob = handle.read()

    if len(blob) < PKG_MIN_BYTES:
        sys.exit("gen_pkg_blob: %s hat nur %d Bytes - das ist kein Paket. "
                 "Ein abgebrochener Paketbau? pkg/build.ps1 neu laufen lassen."
                 % (pkg_path, len(blob)))
    if blob[:4] != PKG_MAGIC:
        sys.exit("gen_pkg_blob: %s beginnt nicht mit der PS5-Paketkennung "
                 "7F 46 49 48, sondern mit %s." % (pkg_path, blob[:4].hex(" ")))
    return blob


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_pkg_blob.py <output.c> [pkg-file]")

    out_path = sys.argv[1]
    pkg_path = (sys.argv[2] if len(sys.argv) > 2 else "") or None

    blob = read_package(pkg_path) if pkg_path else b""

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/* Generated by tools/gen_pkg_blob.py — do not edit. */\n")
        out.write('#include "tile_pkg.h"\n\n')

        if blob:
            out.write("const unsigned char ps5tm_tile_pkg[] = {\n")
            for i in range(0, len(blob), 16):
                row = ", ".join("0x%02x" % b for b in blob[i:i + 16])
                out.write("  %s,\n" % row)
            out.write("};\n")
        else:
            # A zero-length array is not valid C, so keep one filler byte and
            # let the length tell the truth.
            out.write("const unsigned char ps5tm_tile_pkg[] = { 0 };\n")

        out.write("const unsigned long ps5tm_tile_pkg_len = %d;\n" % len(blob))

    if blob:
        print("gen_pkg_blob: %s eingebettet (%d KiB) -> %s"
              % (os.path.basename(pkg_path), len(blob) // 1024, out_path))
    else:
        print("gen_pkg_blob: kein PKG gefunden — Installer sucht zur Laufzeit "
              "auf der Konsole. -> %s" % out_path)


if __name__ == "__main__":
    main()
